### ISSUE TITLE
Allow color/size export

### ISSUE THREAD

**Issue by pragunap2e** [gephi/gephi-lite#113]
After editing the graph, allow color/size of nodes / edges to be stored locally.

**Comment by wey-gu** [comment]
+1, I hope this could be added, too

**Comment by pragunap2e** [comment]
hi, @sim51 is this possible

**Comment by wey-gu** [comment]
I did not examine the example file, but that information remained there as they were color-sized after the initial load.

**Comment by sim51** [comment]
I don't really see what you mean by "allow color/size of nodes / edges to be stored locally".

What I can say is when you change the color, size, etc of a graph,  save it locally (ie export it as a gexf),  and then you load it in gephi-lite, you lost what you have done in the appearance panel. 
is it your issue ?

**Comment by pragunap2e** [comment]
yes, for example if I change color / size and save as local graph, then it won't be present when it is reloaded. Layout changes are loadable. After saving the first graph the second one is loaded.

![saving_this](https://github.com/gephi/gephi-lite/assets/138557805/b171f25d-a370-44c5-abdb-407cd405e211)
![saved_after](https://github.com/gephi/gephi-lite/assets/138557805/6eb8e515-8cfe-457f-ac4d-139334127b62)

**Comment by sim51** [comment]
Thanks for your reply and the screenshot, the issue is well defined now.

FYI, the gexf format is not good enough right now for our use-case (we also work on the next syntax of gexf format).

On nodes, gexf has the following attributes : size, color, label and properties.  When you load a graph on gephi-lite per default, we took those values.
We can do a GEXF export that override the size, color, label properties on each node, but you will loose all the initial values and the legend on the graph.
There is no way  to store in GEXF (actual version) file that the color of node should be taken from a specific property of the node.

During our next sprint on gephi-lite, we will discuss the file formats that we want to use on gephi-lite.

**Comment by wey-gu** [comment]
Thanks for the explanation, now I know more about .gexf, it makes sense that we don't override those information when they are parts of the attributes.

Looking forward to the next sprint! @sim51 , gephi-lite is already extra-amazing to me.

**Comment by pragunap2e** [comment]
Thanks @sim51 is there any workaround for now, where I could reset color/ size values from the exported file.

**Comment by sim51** [comment]
Unfortunately, none to my knowledge

**Comment by sim51** [comment]
By discussing with @jacomyal , it's a bug. 
We should export the visible  graph in gexf, even if we lost the caption of the graph (but we don't have the choice for now).

**Comment by wey-gu** [comment]
> By discussing with @jacomyal , it's a bug. 
> 
> We should export the visible  graph in gexf, even if we lost the caption of the graph (but we don't have the choice for now).

Ah... seems we just do the filter of the graph imported Wen exporting and not add attributes of appearance from the appearanceState, if it's good to go, I can try PR to add appearance states into file when exporting, is that ok?

**Comment by jacomyal** [comment]
Hi @wey-gu,
Really sorry, I was with @sim51 today and we discussed this issue and I had a bit of time, I didn't see your latest message first. The fix is pushed and deployed.
You seem to have already taken a good look into the code though, if you see smelly things in the codebase or want to help testing the app or writing more tests, your contributions will be warmly welcome :)

**Comment by wey-gu** [comment]
> Hi @wey-gu,
> 
> Really sorry, I was with @sim51 today and we discussed this issue and I had a bit of time, I didn't see your latest message first. The fix is pushed and deployed.
> 
> You seem to have already taken a good look into the code though, if you see smelly things in the codebase or want to help testing the app or writing more tests, your contributions will be warmly welcome :)

WOW thanks for the quick change and warm welcome!

I really like gephi-lite and will definitely try to contribute in the future!
