### ISSUE TITLE
Suggestion: In Node select dropdown, invert the current order 

### ISSUE THREAD

**Issue by qkhanhpro** [gephi/gephi-lite#152]
Currently in Gephi Lite, when we create an Edge, we are presented with the dropdowns for Source Node and Target Node. 

I am guessing the node list is currently ordered by created time ascending, causing workflows invoving recently created nodes (which is the most common workflow) having to scroll down to the bottom of the list to find most recently created node.

I propose to invert the order, putting the most recently created node on top so that we can immediately select the recently created node when creating edges

**Comment by paulgirard** [comment]
I agree usage wised would be an aid for manual editing usecases to reverse the order.
I've just checked and yes actually the order is as you've supposed linked to order of insertion of node.
Guaranted by ecmascript >2015 : https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/
