### ISSUE TITLE
Layout number inputs broken 

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#160]
for slow down and edge influence inputs (check others):
- [x]  input dose not accept float value (hit enter shows a invalid message)
- [x] step should be 0.1

**Comment by sim51** [comment]
If I put a float number with a coma instead of a point (ex: `1,6` instead of `1.6`), I have no error and I can't start the layout. 
The start button is not disable, I can click on it, but nothing happened

BTW, to see the modifications, I had to click on "Reset application state" button

**Comment by sim51** [comment]
I also found an error on boolean input. I fixed it. 
To reproduce it, just click on the Guess setting button two times. The `strong gravity mode` is  then disabled ...

Due to the remove of the form validation, now we can send bad data (like the `1,6` in my previous comment). 
I added a try/catch and notify of the error when you start a layout. So even if we don't prevent the layout to stat, the user will have a feedback that there is something wrong. And the graphology error are really good : "graphology-layout-forceatlas2/worker: the `edgeWeightInfluence` setting should be a number."
