### ISSUE TITLE
Page freezes when clicking on a node

### ISSUE THREAD

**Issue by Splines** [gephi/gephi-lite#173]
When loading a graph with 5000 nodes and 18644 edges, navigating in the graph works flawlessly. I can also hover on nodes to see their neighbors. When I click on any node though, the browser tab freezes completely and I can't do anything in the interface anymore.

You can find the .graphml file [here](https://heibox.uni-heidelberg.de/f/c3674931518d4b9498f5/).

## Specs
- Brave Browser 1.70.123 (Chromium 129.06668.89) (64-bit)
- Windows 10

**Comment by paulgirard** [comment]
Thanks for reporting.
I confirm the behavior.

**Comment by paulgirard** [comment]
Gephi Lite performance issue have been badly impacted by a bug introduced in 0.5.0.
The layout metric algo is expensive and was always calculated whereas it was supposed to be opt out.
It's now fixed in 0.5.1 which is about to be released.
I'll let you close this issue once it's working on your side with the new version.

**Comment by Splines** [comment]
Wow, this was quick. I can confirm that this issue is resolved, thanks!
