### ISSUE TITLE
init.cannot_load_remote

### ISSUE THREAD

**Issue by totetmatt** [gephi/gephi-lite#69]
I'm trying to use this gexf : 
https://gephi.org/gephi-lite/?gexf=https://github.com/totetmatt/gexf/raw/master/hanzi/RawHanzi.gexf

It load the page, but not the graph and displya a `init.cannot_load_remote` error.

Other gexf looks working. Could it be UTF-8 / Weird encoding due to chinese character ?

Tested on Firefox and Chrome on MacOS 12.5.1 M1.

**Comment by sim51** [comment]
You must  use a GH raw url : https://raw.githubusercontent.com/totetmatt/gexf/master/hanzi/RawHanzi.gexf

But even with this link, your file can't be loaded due to a parsing error : `e[(intermediate value)] is undefined`
This error comes from this line of the parser : `id = valueElement.getAttribute('id') || valueElement.getAttribute('for');`

So there is one node without the attribut `id` or the parser can't read chinese character

**Comment by sim51** [comment]
The issue comes from  the `weight` on  edges. 

On your file, `weight` are defined as an attribut of edges like that :

```
      <edge id="3112" source="合" target="亼">
         <viz:color r="128" g="128" b="128"></viz:color>
         <attvalues>
           <attvalue for="weight" value="1.0"></attvalue>
         </attvalues>
       </edge>
```

And this attribute is not declared inside an `<attributs>` node at top of the gexf file.
That's why we got a parsing error. 

If you want to define a `weight` attribut on an edge, without the need to declare it, you can put it as an attribut of the `edge` node : 

```
<edge id="73" source="33" target="11" weight="2.0"/>
```

**Comment by sim51** [comment]
See https://github.com/graphology/graphology/issues/482

**Comment by sim51** [comment]
I updated the `graphology-gexf` dep, and with the work of @Yomguithereal, I added the parameter  `allowUndeclaredAttributes` to the parser.

So now, we can open the given GEXF file without error.
