### ISSUE TITLE
Statistics / metrics block

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#8]
This block offers multiple algorithms to enrich data:

- [x] A list of available algorithms is displayed, grouped by types similar to Gephi's ones ("Network Overview", "Community Detection"...)
- [x] The algorithms are picked in graphology's [standard library](https://graphology.github.io/standard-library/)
- [x] Each algorithm offers a `Run` button that opens a modal with the algorithm settings (created attribute name, override existing data or not, algorithm parameters)
- [ ] While the algorithm is running, a loader fills the modal
- [ ] Once it's done, available information about the result is displayed (mimicking Gephi, again)
- [ ] Instead of using an existing algorithm, the user can also select a `Custom scripted attribute` option, that allows them to write a JavaScript function that takes each node and a copy of the graph as input and should return a value

Some more decisions after discussion:
- [ ] Those algorithms are always computed in a worker, to prevent freezing the UI (but the user still can't do anything during that computation)
- [x] The user can always choose the name of the node or edge attribute to use to store the computed data
- [x] The user is informed when they use an attribute name that is already used, and can choose if it should override everything (with empty values for the invisible items) or if it should only override new values
- [ ] The user is warned when they use an attribute name that is already used with a different data type

**Comment by Yomguithereal** [comment]
From #7:

> Else it asks the question of computing graph-level metrics (it might be answered in another issue beware). I am not fan of how Gephi handles this and needing to click on a button to compute constant-time metrics feels weird. But it makes sense for costly metrics such as diameter.

**Comment by Yomguithereal** [comment]
One takeaway from Nansi: we chose not to let the user trigger metric computation as we already precompute handpicked ones when the graph is parsed and those metrics can be selected as visual variables tweaking options automatically. This is quite convenient in streamlined scenarios but has the drawback that it cannot work with costly computations (betweenness centrality is the obvious example here). So the issue we have now in nansi is mixed behavior between precomputing some metrics, some other not, based on the graph's size. This seems weird.

On another note: I don't like the fact that you cannot do anything when computing a costly metric on Gephi as the UI (and sometimes even your PC lol because it eats all of the available CPU time). I would love that metrics are computed asynchronously in a worker in the background while you still can explore the graph and do other stuff in the meantime. But it poses other challenges if we allow mutation of the graph data of course.

**Comment by paulgirard** [comment]
As discussed in #13 and #9, Stats/metrics could be designed as graph/node/edge attributes creation tools.
By framing it like this would allow to :

- let the user decide in which node attribute to store the result
- possibly store multiple versions concurrently (see modularity experiments)
- put the attributes at the center of the usage flow of the app which would then be a data-driven one

This metrics block could then be implemented as a modal which can be invoked from different places in the app : where node/edge attributes are listed/selected, i.e. in appearance and filters for node/edge and in graph summary.

**Comment by boogheta** [comment]
> I would love that metrics are computed asynchronously in a worker in the background while you still can explore the graph and do other stuff in the meantime. But it poses other challenges if we allow mutation of the graph data of course (it smells of locking).

It feels like in the current spec, the objective of having a loader fill the modal during the computation requires the metrics to be computed asynchronously in any case if we want the loader to be animated?
